# Generated by Django 4.0.5 on 2022-11-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='endereço',
            field=models.CharField(max_length=35),
        ),
    ]
