# Generated by Django 4.0.5 on 2022-11-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_person_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='endereco',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
